5 convert social icons to widget
SmruthyJoseph/Big-Store pull request #18
Opened 2021-03-03 08:20 UTC by SmruthyJoseph

#6 converted social icons to block.

2021-03-09 08:50 UTC, AbhijithHaridas requested changes

2021-03-09 08:50 UTC, AbhijithHaridas commented on app/design/frontend/BigStore/Theme/Magento_Theme/templates/social.phtml
> +<li><a href="#" class="icon dribbble"><i class="fab fa-dribbble" aria-hidden="true"></i><span></span></a></li>
How do we customize the social links?

2021-03-10 05:17 UTC, SmruthyJoseph commented
merge conflict solved.

2021-03-11 15:16 UTC, AbhijithHaridas requested changes
@SmruthyJoseph 

Where is the template for the social icons?
Haven't you did what I told you to do?

2021-03-11 15:16 UTC, AbhijithHaridas commented on app/design/frontend/BigStore/Theme/Magento_Theme/templates/html/header/logo.phtml
> +					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('your_block_identifier')->toHtml(); ?>
@SmruthyJoseph why does the block identifier is **your_block_identifier** ???

2021-03-12 03:42 UTC, SmruthyJoseph commented on app/design/frontend/BigStore/Theme/Magento_Theme/templates/html/header/logo.phtml
> +					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('your_block_identifier')->toHtml(); ?>
social icons template are created as cms block. 
I did change the class 'social-top' to a div so the problem solved without accessing arquments since styles are applied on 'social-top' class.

2021-03-12 03:42 UTC, SmruthyJoseph commented on app/design/frontend/BigStore/Theme/Magento_Theme/templates/html/header/logo.phtml
> +					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('your_block_identifier')->toHtml(); ?>
Sorry, i will chnage the block identifier.

2021-03-12 03:50 UTC, SmruthyJoseph commented
social icons cms block identified updated.

2021-03-12 08:45 UTC, merged