1 big store theme
SmruthyJoseph/Big-Store pull request #2
Opened 2021-02-23 07:16 UTC by SmruthyJoseph

BigStore theme development completed.

2021-02-24 11:55 UTC, AbhijithHaridas requested changes
@SmruthyJoseph please remove unnecessary file changes (.htaccess, Readme)

2021-02-24 12:09 UTC, SmruthyJoseph commented
ok

2021-02-24 13:16 UTC, SmruthyJoseph commented
#1 Files .htaccess and readme deleted.

2021-02-25 07:54 UTC, AbhijithHaridas approved these changes

2021-02-25 07:54 UTC, merged